import { IsNotEmpty, IsOptional, IsString, IsBoolean, IsObject, IsDateString } from 'class-validator';

export class CreateReportDto {
  @IsNotEmpty()
  @IsString()
  title: string;

  @IsNotEmpty()
  @IsDateString()
  date: string;

  @IsNotEmpty()
  @IsObject()
  data: any;

  @IsOptional()
  @IsObject()
  aiAnalysis?: any;

  @IsOptional()
  @IsBoolean()
  isAutoGenerated?: boolean;

  @IsOptional()
  @IsString()
  generatedBy?: string;
}
